title:luckyme
author: sidharth
email: dracarys@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  you know nothing jon snow...

# social links
twitter_username: deadpool
github_username:  dead-p..l

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
